apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculator-app
  labels:
    app: calculator-app
    # CircleCI Deploys required labels
    circleci.com/component-name: calculator-app
    circleci.com/environment-name: production
  annotations:
    # CircleCI Deploys required annotation (replace with your project ID)
    circleci.com/project-id: "82cf6c89-5995-4fae-881f-336af18d4d50"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        app: calculator-app
        # CircleCI Deploys required labels for pods
        circleci.com/component-name: calculator-app
        circleci.com/environment-name: production
    spec:
      containers:
      - name: calculator-app
        image: minjun6251/calculator-app:latest
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5 