apiVersion: v1
kind: Service
metadata:
  name: calculator-app-service
  labels:
    app: calculator-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: calculator-app 